#!/bin/bash
export JSON_PATH=`pwd`/even_json
export ONOS_IP="192.168.3.1"
echo "create even67\n"
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' http://$ONOS_IP/mars/v1/devices -d @"$JSON_PATH"even67 --user onos:rocks
sleep 5
echo "create even68\n"
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' http://$ONOS_IP/mars/v1/devices -d @"$JSON_PATH"even68 --user onos:rocks
sleep 5
echo "create even69\n"
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' http://$ONOS_IP/mars/v1/devices -d @"$JSON_PATH"even69 --user onos:rocks
sleep 5
echo "create even70\n"
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' http://$ONOS_IP/mars/v1/devices -d @"$JSON_PATH"even70 --user onos:rocks
