#!/bin/bash
export JSON_PATH=`pwd`/json/
export ONOS_IP="192.168.3.1"
echo "create Policy Router p1"
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' http://$ONOS_IP/mars/tenantlogicalrouter/v1/tenants/t1/r1/policy-route -d @"$JSON_PATH"policy1_192.168.1.1 --user onos:rocks
sleep 1
